module Consts where

import Test.QuickCheck

minLitBound :: Int
minLitBound = -100

maxLitBound :: Int
maxLitBound = 100

maxTupleSize :: Int 
maxTupleSize = 5

maxListSize :: Int
maxListSize = 10

maxParamSize :: Int
maxParamSize = 5

maxConstrSize :: Int 
maxConstrSize = 5

maxCaseAltSize :: Int
maxCaseAltSize = 5

varNames = ["x", "y", "z", "a", "b", "c", "n", "m", "k", "i", "j", "s", "t", 
            "f", "g", "h", "l", "r", "u", "v", "w", "e", "d", "p", "q", "xs", 
            "ys", "zs", "as", "bs", "cs", "ns", "ms", "ks", "is", "js", "ss", 
            "ts", "fs", "gs", "hs", "ls", "rs", "us", "vs", "ws", "es", "ds", 
            "ps", "qs", "x1", "x2", "x3", "y1", "y2", "y3", "z1", "z2", "z3", 
            "a1", "a2", "a3", "b1", "b2", "b3", "c1", "c2", "c3", "n1", "n2", 
            "n3", "m1", "m2", "m3", "k1", "k2", "k3", "i1", "i2", "i3", "j1", 
            "j2", "j3", "s1", "s2", "s3", "t1", "t2", "t3", "f1", "f2", "f3", 
            "g1", "g2", "g3", "h1", "h2", "h3", "l1", "l2", "l3", "r1", "r2", 
            "r3", "u1", "u2", "u3", "v1", "v2", "v3", "w1", "w2", "w3", "e1", 
            "e2", "e3", "d1", "d2", "d3", "p1", "p2", "p3", "q1", "q2", "q3"]

funNames = ["print", "input", "len", "range", "int", "float", "str", "bool", 
            "list", "dict", "set", "tuple", "type", "id", "dir", "help", 
            "abs", "max", "min", "sum", "sorted", "reversed", "map", "filter", 
            "reduce", "zip", "enumerate", "iter", "next", "open", "close", 
            "read", "write", "append", "seek", "tell", "format", "join", 
            "split", "replace", "find", "index", "count", "upper", "lower", 
            "capitalize", "title", "strip", "lstrip", "rstrip", "isdigit", 
            "isalpha", "isalnum", "isspace", "startswith", "endswith", "in", 
            "import", "from", "def", "return", "lambda", "if", "else", "elif", 
            "for", "while", "break", "continue", "pass", "assert", "raise", "try", 
            "except", "finally", "with", "as", "class", "object", "self", "super", 
            "init", "del", "repr", "str", "eq", "ne", "lt", "le", "gt", "ge", 
            "add", "sub", "mul", "truediv", "floordiv", "mod", "pow", "and", "or", 
            "not", "is", "is not", "None", "True", "False", "global", "nonlocal", 
            "yield", "async", "await", "awaitable", "coroutine", "generator", 
            "decorator", "annotation", "docstring", "module", "package", "script", 
            "namespace", "scope", "variable", "function", "method", "attribute", 
            "property", "parameter", "argument", "keyword", "operator", 
            "expression", "statement", "block", "indentation", "comment", 
            "string", "number", "integer", "float", "complex", "boolean", 
            "list", "dictionary", "set", "tuple", "slice", "index", "key", 
            "value", "item", "element", "iterable", "iterator", "sequence", 
            "collection", "container", "mutable", "immutable", "hashable", 
            "comparable", "sortable", "callable", "returnable", "subscriptable", 
            "unpackable", "comprehensible", "exception", "error", "warning", 
            "traceback", "stack", "frame", "code", "object", "byte", "bytecode", 
            "source", "file", "path", "name", "alias", "import", "from", "as", 
            "sys", "os", "math", "random", "datetime", "time", "re", "json", 
            "csv", "xml", "html", "requests", "urllib", "socket", "threading", 
            "multiprocessing", "subprocess", "queue", "asyncio", "tkinter", 
            "pygame", "numpy", "pandas", "matplotlib", "scipy", "sklearn", 
            "tensorflow", "pytorch", "nltk", "spacy", "gensim", "flask", 
            "django", "sqlalchemy", "sqlite3", "mysql", "postgresql", "mongodb",
            "redis", "kafka", "rabbitmq", "celery", "docker", "kubernetes", 
            "ansible", "git", "github", "jupyter", "vscode", "pycharm", "pylint", 
            "pytest", "unittest", "doctest", "sphinx", "setuptools", "pip", 
            "virtualenv", "conda", "poetry", "pypi", "anaconda", "colab",             
            "kaggle", "binder", "heroku", "aws", "azure", "gcp", "ibm", 
            "oracle", "digitalocean", "linode", "namecheap", "godaddy", 
            "cloudflare", "let's encrypt", "ssl", "tls", "http", "https", 
            "ftp", "ssh", "scp", "sftp", "telnet", "ping", "traceroute", 
            "nslookup", "whois", "curl", "wget", "postman", "soap", "rest", 
            "graphql", "api", "web", "server", "client", "browser", "chrome", 
            "firefox", "edge", "safari", "opera", "ie", "html", "css", "js", 
            "jquery", "bootstrap", "react", "angular", "vue", "node", "express", 
            "php", "laravel", "ruby", "rails", "java", "spring", "c#", ".net", 
            "go", "rust", "swift", "kotlin", "dart", "flutter", "r", "shiny", 
            "sql", "nosql", "xml", "yaml", "toml", "ini", "csv", "tsv", "pdf", 
            "docx", "xlsx", "pptx", "txt", "md", "rst", "tex", "latex", "epub", 
            "mobi", "azw", "mp3", "mp4", "avi", "mkv", "jpg", "png", "gif", "svg", 
            "bmp", "tiff", "webp", "zip", "rar", "tar", "gz", "bz2", "xz", "7z", 
            "iso", "exe", "dll", "so", "dylib", "py", "pyd", "pyc", "pyo", "ipynb", 
            "js", "jsx", "ts", "tsx", "cs", "csx", "java", "class", "jar", "war", 
            "go", "rb", "pl", "pm", "sh", "bash", "zsh", "fish", "csh", "tcsh", 
            "ksh", "awk", "sed", "grep", "egrep", "fgrep", "cut", "paste", "sort", 
            "uniq", "wc", "head", "tail", "cat", "tac", "more", "less", "nano", 
            "vi", "vim", "emacs", "ed", "diff", "patch", "make", "cmake", "rake", 
            "ant", "maven", "gradle", "sbt", "npm", "yarn", "webpack", "gulp", 
            "grunt", "bower", "composer", "gem", "cargo", "pip", "easy_install", 
            "pipenv", "venv", "virtualenv", "conda", "poetry", "flit", "flake8", 
            "black", "isort", "yapf", "autopep8", "pylint", "pyflakes", 
            "pycodestyle", "pep8", "pep257", "pydocstyle", "bandit", "mypy", 
            "pytype", "pyright", "pyre", "jedi", "rope", "pytest", "unittest", 
            "doctest", "nose", "nosetests", "pytest-cov", "coverage", "hypothesis",
            "tox", "nox", "travis", "appveyor", "circleci", "github actions", 
            "azure devops", "gitlab ci", "jenkins", "codeship", "codecov", 
            "coveralls", "codacy", "sonarqube", "sonarcloud", "landscape", 
            "prospector", "radon", "wily", "vulture", "pyroma", "interrogate", 
            "check-manifest", "twine", "setuptools", "wheel", "distutils", 
            "pbr", "scikit-build", "cffi", "cython", "pybind11", "numpy", 
            "scipy", "pandas", "matplotlib", "seaborn", "plotly", "bokeh", 
            "altair", "holoviews", "geopandas", "shapely", "folium", "basemap", 
            "cartopy", "pyproj", "rasterio", "gdal", "fiona", "ogr", 
            "rasterstats", "zarr", "xarray", "dask", "modin", "ray", "vaex", 
            "rapids", "cudf", "cuml", "cupy", "numba", "pytorch", "tensorflow", 
            "keras", "mxnet", "jax", "flax", "pyro", "edward", "pymc3", "emcee", 
            "gpytorch", "gpflow", "sklearn", "statsmodels", "patsy", "lifelines", 
            "linearmodels", "pygam", "glmnet", "xgboost", "lightgbm", "catboost", 
            "ngboost", "shap", "lime", "eli5", "mlflow", "dvc", "kedro", "luigi", 
            "airflow", "prefect", "dagster", "dbt", "great expectations", "feast", 
            "tfx", "kubeflow", "seldon", "bentoML", "clipper", "cortex", "fastapi", 
            "flask", "django", "starlette", "uvicorn", "gunicorn", "waitress", 
            "sanic", "tornado", "aiohttp", "requests", "urllib", "httpx", 
            "scrapy", "beautifulsoup", "lxml", "html5lib", "selenium", "playwright", 
            "pyppeteer", "splash", "mechanicalsoup", "robobrowser", "feedparser", 
            "newspaper", "readability", "goose", "textract", "pdfminer", "pypdf2", 
            "camelot", "tabula", "pdftotext", "tika", "fitz", "ghostscript", 
            "poppler", "imagemagick", "pillow", "opencv", "scikit-image", "mahotas", 
            "simplecv", "pytesseract", "pyocr", "wand", "ocrmypdf", "pdfplumber", 
            "nltk", "spacy", "gensim", "textblob", "polyglot", "flair", "transformers", 
            "allennlp", "stanza", "corenlp", "opennlp", "maltparser", "udpipe", 
            "fasttext", "word2vec", "glove", "elmo", "bert", "gpt", "gpt-2", "gpt-3", 
            "xlnet", "albert", "roberta", "distilbert", "bart", "t5", "electra", 
            "reformer", "bigbird", "longformer", "pegasus", "megatron", 
            "deepspeed", "fairseq", "huggingface", "sentencepiece", "tokenizers", 
            "sacremoses", "moses", "subword-nmt", "bpe", "bpe-dropout", "unmt", "xnmt", 
            "opennmt", "fairseq", "sockeye", "joeynmt", "marian", "bergamot", 
            "ctranslate2", "tensor2tensor", "t2t", "trax", "mesh-tensorflow", 
            "lingvo", "espnet", "kaldi", "wav2letter", "wav2vec", "deepspeech", 
            "vosk", "speechbrain", "pyaudio", "sounddevice", "soundfile", "librosa", 
            "pydub", "pysndfile", "audioread", "aubio", "essentia", "madmom", 
            "crepe", "spleeter", "pyworld", "pysptk", "librosa", "torchaudio", 
            "tensorflow-io", "kapre", "nnAudio", "nnabla", "julius", "pocketsphinx", 
            "cmusphinx", "sphinx4", "festival", "flite", "espeak", "pyttsx", "gTTS", 
            "pico2wave", "marytts", "mimic", "tacotron", "tacotron2", "fastspeech", 
            "fastspeech2", "glow-tts", "waveglow", "wavernn", "waveflow", "wavegan", 
            "wavenet", "parallel-wavenet", "melgan", "multiband-melgan", "pwgan", 
            "mb-melgan", "hifigan", "wavegrad", "wave2vec", "lpcnet", "rnnoise", 
            "speex", "opus", "silk", "amr", "amr-wb", "amr-nb", "gsm", "ilbc", 
            "codec2", "flac", "vorbis", "opus", "mp3", "aac", "ac3", "wma", "alac", 
            "wavpack", "ape", "mpc", "tta", "ofr", "shn", "dsd", "dff", "dsf", 
            "sacd", "iso"]

dataNames = ["Apple", "Beauty", "Dog", "Pain", "School", "Fire", "Cat", "Humor",
             "Island", "Justice", "Kiwi", "Light", "Table", "Cloud", "Glasses", 
             "Peace", "Cheese", "Laughter", "Frog", "Time", "Grape", "Life", 
             "Chess", "Zebra", "Water", "Ball", "House", "Dice", "Energy", 
             "Knife", "Ice", "Story", "Image", "Game", "Pencil", "Music", 
             "Christmas", "Egg", "Bread", "Picture", "Mouse", "Shadow", "Earth", 
             "Bear", "Wind", "Cup", "Zero", "Anchor", "Cake", "Bed", "Tooth", 
             "Star", "Party", "Grass", "Idea", "Window", "Lake", "Magic", 
             "Night", "Eye", "Paper", "Puzzle", "Wheel", "Sun", "Theater", 
             "Nail", "Trip", "Syrup", "Zoo", "Tree", "Bicycle", "Coffee", 
             "Money", "Mirror", "Flower", "Bottle", "Church", "Garden", "Book", 
             "Machine", "Nose", "Ear", "Wall", "Room", "Clock", "Shoe", "Phone", 
             "Belly", "Volcano", "Shawl", "Zipper", "Algebra", "Flag", "Sky", 
             "Drawing", "Sport", "Cold", "Sunflower", "Winter", "Knee", "Orange", 
             "Map", "Knot", "Wave", "Piano", "Burn", "Radio", "Salt", "Cutlery", 
             "Uniform", "Glass", "Xerox", "Buzz", "Love", "Butterfly", "Heart", 
             "Doubt", "Hope", "Hunger", "Taste", "Envy", "Way", "Freedom", "Fear", 
             "Name", "Gold", "Word", "Quality", "Anger", "Longing", "Boredom", 
             "Union", "Will", "Checkmate", "Care", "Joy", "Play", "Affection", 
             "Desire", "Education", "Future", "War", "Childhood", "Youth", "Trash", 
             "Lie", "Nothing", "Opportunity", "Poetry", "Quantity", "Rule", "Health", 
             "Sadness", "Universe", "Truth", "Chess", "Zen"]